# Generated by Django 4.0.6 on 2022-07-17 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.TextField(blank=True, max_length=200, null=True)),
                ('customer_address', models.TextField(blank=True, max_length=200, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('car_model', models.IntegerField(blank=True, null=True)),
                ('car_chassis', models.TextField(blank=True, max_length=20, null=True)),
                ('car_number', models.TextField(blank=True, max_length=20, null=True)),
                ('car_mileage', models.BigIntegerField(blank=True, null=True)),
                ('car_color', models.TextField(blank=True, max_length=50, null=True)),
                ('job_date', models.DateField(default=django.utils.timezone.now)),
                ('job_comments', models.TextField(blank=True, max_length=600, null=True)),
                ('job_notes', models.TextField(blank=True, max_length=600, null=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('service_one', models.TextField(blank=True, default='', max_length=120, null=True, verbose_name='Service 1')),
                ('service_one_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('service_two', models.TextField(blank=True, default='', null=True, verbose_name='Service 2')),
                ('service_two_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('service_three', models.TextField(blank=True, default='', max_length=120, null=True, verbose_name='Service 3')),
                ('service_three_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('service_four', models.TextField(blank=True, default='', max_length=120, null=True, verbose_name='Service 4')),
                ('service_four_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('service_five', models.TextField(blank=True, default='', max_length=120, null=True, verbose_name='Service 5')),
                ('service_five_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('service_six', models.TextField(blank=True, default='', max_length=120, null=True, verbose_name='Service 6')),
                ('service_six_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('service_seven', models.TextField(blank=True, default='', max_length=120, null=True, verbose_name='Service 7')),
                ('service_seven_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('service_eight', models.TextField(blank=True, default='', max_length=120, null=True, verbose_name='Service 8')),
                ('service_eight_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('service_nine', models.TextField(blank=True, default='', max_length=120, null=True, verbose_name='Service 9')),
                ('service_nine_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('service_ten', models.TextField(blank=True, default='', max_length=120, null=True, verbose_name='Service 10')),
                ('service_ten_price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('total', models.BigIntegerField(blank=True, default=0, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Visa ', 'Visa ')], default='', max_length=50, null=True)),
            ],
        ),
    ]
